from .env_vars import env

RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_SITE_KEY')
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_SECRET_KEY')
RECAPTCHA_REQUIRED_SCORE = 0.85

GOOGLE_MEASUREMENT_ID = env('GOOGLE_MEASUREMENT_ID')
