services:
  backend:
    image: likeca/django
    container_name: backend
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/nextjs_django/settings/local.env
    restart: unless-stopped

  frontend:
    image: likeca/nextjs
    container_name: frontend
    build:
      context: frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
