services:
  backend:
    image: likeca/django
    container_name: backend
    build:
      context: backend
    network_mode: host
    env_file:
      - backend/backend/settings/local.env
    restart: unless-stopped

  frontend:
    image: likeca/nextjs
    container_name: frontend
    build:
      context: frontend
    network_mode: host
    env_file:
      - frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
