services:
  backend:
    image: likeca/django
    container_name: django
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - backend/nextjs_django/settings/local.env

  frontend:
    image: likeca/nextjs
    container_name: nextjs
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
