from .env_vars import env

EMAIL_CONFIG = env.email_url('EMAIL_URL', default='consolemail://')
if 'smtp' in EMAIL_CONFIG['EMAIL_BACKEND']:
    EMAIL_USE_TLS = EMAIL_CONFIG['EMAIL_USE_TLS']
    EMAIL_HOST = EMAIL_CONFIG['EMAIL_HOST']
    EMAIL_PORT = EMAIL_CONFIG['EMAIL_PORT']
    EMAIL_HOST_USER = EMAIL_CONFIG['EMAIL_HOST_USER']
    EMAIL_HOST_PASSWORD = EMAIL_CONFIG['EMAIL_HOST_PASSWORD']

WEBMASTERS = eval(env("WEBMASTERS"))
